name: Mixeway Scan Pipeline
on:
  push:
    branches:
      - '*'
jobs:
  mixeway-scan:
    name: Mixeway Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo
          ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
      - name: Prepare Mixeway docker image
        run: |
          docker pull mixeway/scanner:latest
      - name: Run Scan
        run: |
          docker run -e MODE=STANDALONE -e OSS_USERNAME={{secrets.OSS_USERNAME}}  -e OSS_KEY={{secrets.OSS_KEY}} -v "$(pwd):/opt/sources" mixeway/scanner:latest -e COMMIT_ID=${{steps.vars.outputs.sha_short}} -e BRANCH=${{steps.vars.outputs.branch}} -e MIXEWAY_PROJECT_NAME=jsokolowska_lab_secure_app -e MIXEWAY_PROJECT_ID=123 -e MIXEWAY_KEY={{secrets.MIXEWAY_KEY}}
